### ISSUE TITLE
Conversion function

### ISSUE THREAD

**Issue by KittyGiraudel** [cahnory/PlastiCSS#4]
I feel like all your conversion functions could be merged into a single one with something like this (warning, code not tested):

``` scss
@function to($unit, $value, $coef: 1) {
  $units: 1cm 1mm 1ch 1px 1em 1rem 1vw 1vh 1vmin 1vmax 1pica 1ex 1in 1pc 1%;
  $available-units: cm mm ch px em rem vw vh vmin vmax pica ex in pc %; 
  $index: index($available-units, $unit);

  @if $index {
    @return nth($units, $index) * to-number($value, $coef);
  }

  @warn "Unknown unit `#{$unit}` for `to`.";
  @return false;
}
```
